/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alt_java_lang_Class2 */

#ifndef _Included_alt_java_lang_Class2
#define _Included_alt_java_lang_Class2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alt_java_lang_Class2
 * Method:    isInterface
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_alt_java_lang_Class2_isInterface
  (JNIEnv *, jobject);

/*
 * Class:     alt_java_lang_Class2
 * Method:    getSuperclass
 * Signature: ()Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_alt_java_lang_Class2_getSuperclass
  (JNIEnv *, jobject);

/*
 * Class:     alt_java_lang_Class2
 * Method:    getInterfaces
 * Signature: ()[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_alt_java_lang_Class2_getInterfaces
  (JNIEnv *, jobject);

/*
 * Class:     alt_java_lang_Class2
 * Method:    newInstance
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_alt_java_lang_Class2_newInstance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
