/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alt_java_lang_Object2 */

#ifndef _Included_alt_java_lang_Object2
#define _Included_alt_java_lang_Object2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alt_java_lang_Object2
 * Method:    getClass2
 * Signature: ()Lalt/java/lang/Class2;
 */
JNIEXPORT jobject JNICALL Java_alt_java_lang_Object2_getClass2
  (JNIEnv *, jobject);

/*
 * Class:     alt_java_lang_Object2
 * Method:    hashCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_alt_java_lang_Object2_hashCode
  (JNIEnv *, jobject);

/*
 * Class:     alt_java_lang_Object2
 * Method:    notify2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_alt_java_lang_Object2_notify2
  (JNIEnv *, jobject);

/*
 * Class:     alt_java_lang_Object2
 * Method:    notifyAll2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_alt_java_lang_Object2_notifyAll2
  (JNIEnv *, jobject);

/*
 * Class:     alt_java_lang_Object2
 * Method:    wait2
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_alt_java_lang_Object2_wait2
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
