/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alt_java_lang_System */

#ifndef _Included_alt_java_lang_System
#define _Included_alt_java_lang_System
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alt_java_lang_System
 * Method:    currentTimeMillis
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_alt_java_lang_System_currentTimeMillis
  (JNIEnv *, jclass);

/*
 * Class:     alt_java_lang_System
 * Method:    arraycopy
 * Signature: (Ljava/lang/Object;ILjava/lang/Object;II)V
 */
JNIEXPORT void JNICALL Java_alt_java_lang_System_arraycopy
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
